---
title: "Overview of SMR related activities" 
author: F. Michel-Sendis
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(data.table)
library(DT)
library(plotly)

topics<-fread('csv/topics.csv')%>%
  mutate(
    TOPIC= factor(TOPIC, levels=TOPIC),
    TOPIC_CLASS= factor(TOPIC_CLASS, levels=c('TECH', 'FRAMEWORK', 'APPLICATION'))
  )

projects<-fread("csv/nea_smrs.csv", header = TRUE, na.strings=c("","NA"))%>%unique()
Nproject<-as.integer(dim(projects)[1])

df<-projects%>%
  select(KEY, PROJECT, DELIVERABLE, DUE_DATE, 13:46)%>%
  pivot_longer(cols = c(16:38), names_to = "TOPIC", values_to = "TOPIC_FLAG")%>%
  mutate(
    TOPIC_FLAG=toupper(TOPIC_FLAG),
    SMR_FLAG=factor(SMR, levels=c('Specific', 'Relevant')))%>%
  merge(topics)%>%
  pivot_longer(cols = c(6:14), names_to = "COMMITTEE", values_to = "COMMITTEE_FLAG")%>%
  mutate(
    COMMITTEE_FLAG=toupper(COMMITTEE_FLAG)
         )%>%
  filter(TOPIC_FLAG=="YES" & COMMITTEE_FLAG=="YES" )%>%
  select(KEY,PROJECT,DELIVERABLE,DUE_DATE,STATUS,SMR_FLAG,
        TOPIC, TOPIC_CLASS, COMMITTEE, -TOPIC_FLAG,-COMMITTEE_FLAG) 

Ncommittees<-as.integer(dim(as.data.frame(unique(df$COMMITTEE)))[1])
                        
```

\vspace{2cm}

# SMR projects per committee

Total number of projects : `r Nproject` SMR related projects found on `r Ncommittees` committees.

Specific projects related to SMRS are found in 6 committees :

```{r histo1, echo=FALSE, fig.width=10, fight.height=70}
library(packcircles)

#df11<-fread("csv/df1.csv")
g<-ggplot(df, aes(y=SMR_FLAG, fill=SMR_FLAG)) +
  geom_bar(stat='count', position = "dodge") +
  theme(legend.position = "top") +
  theme_light() +
  theme(legend.position = "none") +
  facet_wrap(vars(COMMITTEE)) +
  xlab("")+
  ylab("") 
 


df_b<-df%>%select(KEY, SMR_FLAG, COMMITTEE)%>%
  group_by(COMMITTEE, SMR_FLAG)%>%
  count(COMMITTEE, SMR_FLAG)

df_b_s<-df_b%>%filter(SMR_FLAG=='Specific')
df_b_r<-df_b%>%filter(SMR_FLAG=='Relevant')

packing <- circleProgressiveLayout(df_b_s$n, sizetype='area')
dat.gg <- circleLayoutVertices(packing, npoints=50)
data<-cbind(df_b_s, packing)

  
# Make the plot
g<-ggplot() + 
  geom_polygon(data = dat.gg, aes(x, y, group = id, fill=as.factor(id)), colour = "black", alpha = 0.6) +
  geom_text(data = data, aes(x, y, label = COMMITTEE))+
  scale_size_continuous(range = c(1,4)) +
  theme_void() + 
  theme(legend.position="none") +
  coord_equal()

g


```

# SMR Projects per Topic and Committee

```{r scatter3, echo=FALSE, fig.width=10, fight.height=70}

g<-ggplot(df, aes(y=COMMITTEE, fill=TOPIC))+
  geom_bar(stat='count' )+
  facet_wrap(vars(TOPIC_CLASS))

g
```





# SMR topics addressed per committee

```{r histo2, echo=FALSE, fig.width=10, fight.height=70}
g<-ggplot(df, aes(y=SMR_FLAG,  fill=TOPIC)) +
  geom_bar(stat='count', position = "dodge") +
  theme(legend.position = "top") +
  theme_light() + 
  facet_wrap(vars(COMMITTEE)) +
  xlab("")+
  ylab("")  

ggplotly(g)

```

 

# Table

```{r data, echo=FALSE}


DT::datatable(df)

```


